application: drinkbot9000 
version: 1
runtime: python
api_version: 1

handlers:

# run script named same as directory, 
# e.g. http://localhost/foo/ runs foo/foo.py

- url: /(.*\.js)
  static_files: \1
  upload: .*\.js

- url: /(.*?)/.*
  script: \1/\1.py

- url: /.*
  script: home.py