application: drinkbot9000 
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: index.py

- url: /(.*)/.*
  script: \1/\1.py

#- url: /helloworld/helloworld.py
#  script: helloworld/helloworld.py

- url: /.*
#  script: helloworld/helloworld.py
  script: not_found.py